name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.4

    - name: Install just
      uses: extractions/setup-just@v3

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run pre-commit checks
      run: just pre-commit
